apiVersion: v1
kind: Service
metadata:
  name: my-app-service  # Replace with a desired service name
spec:
  selector:
    app: my-app  # Matches the label from the deployment
  ports:
  - port: 80  # Service port (can be different from container port)
    targetPort: 80  # Port the service proxies traffic to in the pods
    protocol: TCP
  type: ClusterIP  # Service exposes pods within the cluster
