apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:7.85.0
    command: ["sh", "-c", "while true; do curl -s http://web-counter-service:8080; sleep 1; done"]
