apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcenter-decrementer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcenter-decrementer
  template:
    metadata:
      labels:
        app: webcenter-decrementer
    spec:
      containers:
      - name: webcenter-decrementer
        image: gcr.io/di-services/testimages/decrement:latest
        ports:
        - containerPort: 8080
