apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: sideproj
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Use the appropriate ingress class
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/healthcheck-path: /health  # Health check path
spec:
  tls:
    - hosts:
      - redis-app.services.deepinstinctweb.com  # Replace with your actual host
      secretName: tls-secret  # TLS secret for HTTPS
  rules:
    - host: redis-app.services.deepinstinctweb.com  # Replace with your actual host
      http:
        paths:
        - pathType: Prefix
          path: "/increment"
          backend:
            service:
              name: webcenter-incrementer-service
              port:
                number: 80
        - pathType: Prefix
          path: "/decrement"
          backend:
            service:
              name: webcenter-decrementer-service
              port:
                number: 80
tls:
  - hosts:
    - nice.services.deepinstinctweb.com
    secretName: tls-secret

