apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incdec-ingress
  namespace: sideproj
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Use the appropriate ingress class
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/healthcheck-path: /health  # Health check path
spec:
  tls:
    - hosts:
      - incdec.services.deepinstinctweb.com  # Replace with your actual host
      secretName: tls-secret  # TLS secret for HTTPS
  rules:
    - host: incdec.services.deepinstinctweb.com  # Replace with your actual host
      http:
        paths:
        - pathType: Prefix
          path: "/increment"
          backend:
            service:
              name: webcenter-increment-service
              port:
                number: 80
        - pathType: Prefix
          path: "/decrement"
          backend:
            service:
              name: webcenter-decrement-service
              port:
                number: 80
# tls:
#   - hosts:
#     - nice.services.deepinstinctweb.com
#     secretName: tls-secret

