apiVersion: v1
kind: Service
metadata:
  name: webcenter-incrementer-service
spec:
  selector:
    app: webcenter-incrementer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webcenter-decrementer-service
spec:
  selector:
    app: webcenter-decrementer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
