apiVersion: v1
kind: Service
metadata:
  name: redis-incrementer-service
spec:
  selector:
    app: redis-incrementer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-decrementer-service
spec:
  selector:
    app: redis-decrementer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
