apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-tester
  template:
    metadata:
      labels:
        app: curl-tester
    spec:
      containers:
      - name: curl
        image: curlimages/curl # Or any other prefered curl image
        command: ["sleep", "infinity"]


        ##curl to curl http://hello-world-clusterip.sideproj.svc.cluster.local